rm ~/Dropbox/Wmass/script/*.d
rm ~/Dropbox/Wmass/script/*.so
rm ~/Dropbox/Wmass/script/*.pcm
rm ~/Dropbox/Wmass/script/*ACLiC*
rm ~/Dropbox/Wmass/script/*.o
rm ~/Dropbox/Wmass/script/*.pyc
rm ~/Dropbox/Wmass/plot_script/*.d
rm ~/Dropbox/Wmass/plot_script/*.so
rm ~/Dropbox/Wmass/plot_script/*.pcm
rm ~/Dropbox/Wmass/plot_script/*ACLiC*
rm ~/Dropbox/Wmass/plot_script/*.o
rm ~/Dropbox/Wmass/plot_script/*.pyc
